---
# Copyright (C) 2021-2024 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Debug output
  ansible.builtin.debug:
    msg: "Checking {{ item.path }} CNI plugin"

- name: Execute CNI plugin to capture output
  ansible.builtin.command:
    cmd: "{{ item.path }}"
  register: version_output
  changed_when: false

- name: Ensure output contains correct version string
  ansible.builtin.assert:
    that:
      - "expected_output in version_output.stderr"
