---
# Copyright (C) 2021-2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted
  when:
    - cni_restart_kubelet
