---
# Copyright (C) 2021-2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- hosts: test-cni-arch
  remote_user: vagrant
  become: true
  gather_facts: false
  tasks:
    - name: Init pacman
      ansible.builtin.raw: |
        pacman-key --init
        pacman-key --populate archlinux
      changed_when: false
      failed_when: false

    - name: Install Python
      ansible.builtin.raw: |
        pacman -S --noconfirm python
      args:
        executable: /bin/bash
      changed_when: false

- hosts: test-cni-ubuntu1804,test-cni-ubuntu2004
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: true
        cache_valid_time: 3600

- hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include CNI role
      include_role:
        name: githubixx.cni
